import random

x = random.randint(1, 64)
y = random.randint(1, 64)
z = random.randint(1, 64)
a = random.randint(1, 64)
b = random.randint(1, 64)
c = random.randint(1, 64)
x_waile = random.randint(1, 378)
y_waile = random.randint(1, 378)
z_waile = random.randint(1, 378)
a_waile = random.randint(1, 378)
b_waile = random.randint(1, 378)
c_waile = random.randint(1, 378)
x_anser = int(input('number 1 (첫 번째 숫자'))
y_anser = int(input('number 2 (두 번째 숫자'))
z_anser = int(input('number 3 (세 번째 숫자'))
a_anser = int(input('number 4 (네 번째 숫자'))
b_anser = int(input('number 5 (다섯 번째 숫자'))
c_anser = int(input('number 6 (여섯 번째 숫자'))
