import time
print ("안녕! 나는 파이썬이라고 해.")
time.sleep(2)
name=input('너의 이름은 무엇이니?')
print ("아 그렇구나!")
time.sleep(2)
print ('아! 그럼 너의 이름은', name, '이구나!')
time.sleep(2)
print (name, '만나서 반가웠어!')
time.sleep(0.5)
print ('그럼 안녕!', name)
time.sleep(0.5)