import time
name = input('당신의 이름은 무엇인가요')
old = int(input('당신의 나이는 얼마인가요'))
print('당신은 이름이 ', name, '(이)군요.')
time.sleep(1)
print('당신은 나이가', old, '살이군요.')
time.sleep(1)
print("저는 이름이 유지우고, 대전에 살고 있습니다.")
time.sleep(1)
print("취미는 게임과 코딩, 독서 입니다.")
time.sleep(1)
number2 = (input('프로그램을 종료하시려면 아무 글자나 입력하세요.'))
